// EffectsPresets.js — Curated real-world effect presets per instrument
// Each preset combines effects + sound settings into a recognizable sound character

// Structure: { name, description, icon (emoji), effects: {...}, sound: {...} }
// effects = same shape as EffectsEngine defaultEffectSettings
// sound = partial overrides for PlayerProvider sound settings (sustain, fade, attack, rate, volume)

const presets = {
  piano: [
    {
      id: "clean",
      name: "Clean",
      description: "Pure acoustic piano, no processing",
      icon: "🎹",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 300, fade: 150, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "concert-hall",
      name: "Concert Hall",
      description: "Grand reverberant hall, classical feel",
      icon: "🏛️",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 12000, Q: 0.3 },
        reverb: { enabled: true, mix: 55, decay: 4.0 },
        delay: { enabled: false, time: 300, feedback: 10, mix: 8 },
        compressor: { enabled: true, threshold: -20, ratio: 2.5 },
      },
      sound: { sustain: 500, fade: 300, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "electric-piano",
      name: "Electric Piano",
      description: "Rhodes/Wurlitzer — warm, bell-like tone",
      icon: "⚡",
      effects: {
        distortion: { enabled: true, amount: 12 },
        filter: { enabled: true, type: "lowpass", frequency: 4500, Q: 1.2 },
        reverb: { enabled: true, mix: 20, decay: 1.5 },
        delay: { enabled: true, time: 280, feedback: 20, mix: 15 },
        compressor: { enabled: true, threshold: -18, ratio: 3 },
      },
      sound: { sustain: 250, fade: 120, attack: 5, rate: 1.0, volume: 2 },
    },
    {
      id: "lofi",
      name: "Lo-fi",
      description: "Vinyl warmth, dusty and mellow",
      icon: "📻",
      effects: {
        distortion: { enabled: true, amount: 8 },
        filter: { enabled: true, type: "lowpass", frequency: 3000, Q: 0.8 },
        reverb: { enabled: true, mix: 25, decay: 1.8 },
        delay: { enabled: false, time: 200, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -22, ratio: 4 },
      },
      sound: { sustain: 200, fade: 100, attack: 10, rate: 0.98, volume: -2 },
    },
    {
      id: "ambient",
      name: "Ambient",
      description: "Ethereal pads, dreamy soundscape",
      icon: "🌊",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: true, type: "lowpass", frequency: 6000, Q: 0.5 },
        reverb: { enabled: true, mix: 65, decay: 4.5 },
        delay: { enabled: true, time: 450, feedback: 40, mix: 35 },
        compressor: { enabled: true, threshold: -25, ratio: 2 },
      },
      sound: { sustain: 600, fade: 400, attack: 80, rate: 1.0, volume: -3 },
    },
    {
      id: "honky-tonk",
      name: "Honky Tonk",
      description: "Saloon piano — bright and twangy",
      icon: "🤠",
      effects: {
        distortion: { enabled: true, amount: 15 },
        filter: { enabled: true, type: "highpass", frequency: 800, Q: 1.5 },
        reverb: { enabled: true, mix: 30, decay: 1.2 },
        delay: { enabled: false, time: 150, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -15, ratio: 5 },
      },
      sound: { sustain: 150, fade: 80, attack: 0, rate: 1.02, volume: 2 },
    },
  ],

  "grand-piano": [
    {
      id: "clean",
      name: "Clean",
      description: "Pure concert grand",
      icon: "🎹",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 400, fade: 200, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "steinway-hall",
      name: "Steinway Hall",
      description: "Rich, resonant concert grand in a large hall",
      icon: "🏛️",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 14000, Q: 0.3 },
        reverb: { enabled: true, mix: 50, decay: 4.5 },
        delay: { enabled: false, time: 300, feedback: 5, mix: 3 },
        compressor: { enabled: true, threshold: -22, ratio: 2 },
      },
      sound: { sustain: 600, fade: 350, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "cinematic",
      name: "Cinematic",
      description: "Film score piano — epic and emotional",
      icon: "🎬",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: true, type: "lowpass", frequency: 8000, Q: 0.5 },
        reverb: { enabled: true, mix: 55, decay: 3.5 },
        delay: { enabled: true, time: 400, feedback: 25, mix: 20 },
        compressor: { enabled: true, threshold: -20, ratio: 3 },
      },
      sound: { sustain: 500, fade: 300, attack: 30, rate: 1.0, volume: 2 },
    },
    {
      id: "intimate",
      name: "Intimate",
      description: "Close-mic'd, warm and personal",
      icon: "🕯️",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: true, type: "lowpass", frequency: 6000, Q: 0.3 },
        reverb: { enabled: true, mix: 15, decay: 1.0 },
        delay: { enabled: false, time: 200, feedback: 5, mix: 3 },
        compressor: { enabled: true, threshold: -18, ratio: 3 },
      },
      sound: { sustain: 350, fade: 180, attack: 0, rate: 1.0, volume: -1 },
    },
  ],

  keyboard: [
    {
      id: "clean",
      name: "Clean",
      description: "Unprocessed keyboard",
      icon: "🎹",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 220, fade: 100, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "synth-pad",
      name: "Synth Pad",
      description: "Lush, evolving synth texture",
      icon: "🌈",
      effects: {
        distortion: { enabled: false, amount: 5 },
        filter: { enabled: true, type: "lowpass", frequency: 5000, Q: 1.5 },
        reverb: { enabled: true, mix: 45, decay: 3.0 },
        delay: { enabled: true, time: 350, feedback: 35, mix: 30 },
        compressor: { enabled: true, threshold: -20, ratio: 2.5 },
      },
      sound: { sustain: 500, fade: 300, attack: 60, rate: 1.0, volume: -2 },
    },
    {
      id: "organ",
      name: "Organ",
      description: "Hammond-style — warm overdrive",
      icon: "⛪",
      effects: {
        distortion: { enabled: true, amount: 30 },
        filter: { enabled: true, type: "lowpass", frequency: 4000, Q: 1.0 },
        reverb: { enabled: true, mix: 30, decay: 2.0 },
        delay: { enabled: false, time: 200, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -15, ratio: 4 },
      },
      sound: { sustain: 400, fade: 80, attack: 0, rate: 1.0, volume: 2 },
    },
    {
      id: "retro-keys",
      name: "Retro Keys",
      description: "70s/80s electric keyboard vibe",
      icon: "🕺",
      effects: {
        distortion: { enabled: true, amount: 10 },
        filter: { enabled: true, type: "lowpass", frequency: 5500, Q: 1.2 },
        reverb: { enabled: true, mix: 20, decay: 1.5 },
        delay: { enabled: true, time: 250, feedback: 25, mix: 20 },
        compressor: { enabled: true, threshold: -18, ratio: 3 },
      },
      sound: { sustain: 260, fade: 120, attack: 5, rate: 1.0, volume: 0 },
    },
    {
      id: "space-keys",
      name: "Space Keys",
      description: "Sci-fi, atmospheric, otherworldly",
      icon: "🚀",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: true, type: "bandpass", frequency: 3000, Q: 3.0 },
        reverb: { enabled: true, mix: 60, decay: 4.0 },
        delay: { enabled: true, time: 500, feedback: 50, mix: 40 },
        compressor: { enabled: true, threshold: -25, ratio: 2 },
      },
      sound: { sustain: 600, fade: 400, attack: 100, rate: 0.9, volume: -3 },
    },
  ],

  guitar: [
    {
      id: "clean",
      name: "Clean",
      description: "Pure acoustic guitar",
      icon: "🎸",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 250, fade: 120, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "blues",
      name: "Blues",
      description: "Warm breakup, smoky tone",
      icon: "🎷",
      effects: {
        distortion: { enabled: true, amount: 25 },
        filter: { enabled: true, type: "lowpass", frequency: 5000, Q: 0.8 },
        reverb: { enabled: true, mix: 30, decay: 2.0 },
        delay: { enabled: false, time: 250, feedback: 15, mix: 10 },
        compressor: { enabled: true, threshold: -20, ratio: 3 },
      },
      sound: { sustain: 300, fade: 150, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "spanish",
      name: "Spanish",
      description: "Nylon string, flamenco style",
      icon: "💃",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: true, type: "highpass", frequency: 200, Q: 0.5 },
        reverb: { enabled: true, mix: 35, decay: 2.5 },
        delay: { enabled: false, time: 200, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -22, ratio: 2.5 },
      },
      sound: { sustain: 350, fade: 200, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "campfire",
      name: "Campfire",
      description: "Warm, intimate picking by the fire",
      icon: "🔥",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: true, type: "lowpass", frequency: 4000, Q: 0.5 },
        reverb: { enabled: true, mix: 20, decay: 1.5 },
        delay: { enabled: false, time: 200, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -18, ratio: 3 },
      },
      sound: { sustain: 300, fade: 180, attack: 0, rate: 1.0, volume: -2 },
    },
    {
      id: "surf-rock",
      name: "Surf Rock",
      description: "Dick Dale spring reverb, twangy",
      icon: "🏄",
      effects: {
        distortion: { enabled: true, amount: 15 },
        filter: { enabled: true, type: "highpass", frequency: 400, Q: 1.0 },
        reverb: { enabled: true, mix: 60, decay: 1.5 },
        delay: { enabled: false, time: 150, feedback: 15, mix: 10 },
        compressor: { enabled: true, threshold: -15, ratio: 4 },
      },
      sound: { sustain: 200, fade: 80, attack: 0, rate: 1.0, volume: 2 },
    },
  ],

  "electric-guitar": [
    {
      id: "clean",
      name: "Clean",
      description: "Crystal clear Fender clean",
      icon: "✨",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: true, mix: 15, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: true, threshold: -20, ratio: 2 },
      },
      sound: { sustain: 250, fade: 100, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "overdrive",
      name: "Overdrive",
      description: "Tube amp crunch, classic rock",
      icon: "🔥",
      effects: {
        distortion: { enabled: true, amount: 45 },
        filter: { enabled: true, type: "lowpass", frequency: 6000, Q: 1.0 },
        reverb: { enabled: true, mix: 15, decay: 1.2 },
        delay: { enabled: false, time: 200, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -18, ratio: 4 },
      },
      sound: { sustain: 300, fade: 120, attack: 0, rate: 1.0, volume: 2 },
    },
    {
      id: "metal",
      name: "Metal",
      description: "High-gain, aggressive, tight",
      icon: "🤘",
      effects: {
        distortion: { enabled: true, amount: 80 },
        filter: { enabled: true, type: "lowpass", frequency: 5000, Q: 2.0 },
        reverb: { enabled: false, mix: 5, decay: 0.5 },
        delay: { enabled: false, time: 100, feedback: 5, mix: 3 },
        compressor: { enabled: true, threshold: -12, ratio: 8 },
      },
      sound: { sustain: 200, fade: 60, attack: 0, rate: 1.0, volume: 3 },
    },
    {
      id: "shoegaze",
      name: "Shoegaze",
      description: "Wall of sound — reverb, fuzz, dreamy",
      icon: "👟",
      effects: {
        distortion: { enabled: true, amount: 40 },
        filter: { enabled: true, type: "lowpass", frequency: 4000, Q: 1.5 },
        reverb: { enabled: true, mix: 70, decay: 4.0 },
        delay: { enabled: true, time: 400, feedback: 45, mix: 35 },
        compressor: { enabled: true, threshold: -20, ratio: 3 },
      },
      sound: { sustain: 500, fade: 350, attack: 50, rate: 1.0, volume: 0 },
    },
    {
      id: "funk",
      name: "Funk",
      description: "Wah-like filter, tight and punchy",
      icon: "🕺",
      effects: {
        distortion: { enabled: true, amount: 15 },
        filter: { enabled: true, type: "bandpass", frequency: 2000, Q: 5.0 },
        reverb: { enabled: false, mix: 10, decay: 0.8 },
        delay: { enabled: false, time: 150, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -15, ratio: 5 },
      },
      sound: { sustain: 150, fade: 60, attack: 0, rate: 1.0, volume: 2 },
    },
  ],

  banjo: [
    {
      id: "clean",
      name: "Clean",
      description: "Pure banjo twang",
      icon: "🪕",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 200, fade: 100, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "bluegrass",
      name: "Bluegrass",
      description: "Front porch, fast picking energy",
      icon: "🌾",
      effects: {
        distortion: { enabled: false, amount: 5 },
        filter: { enabled: true, type: "highpass", frequency: 300, Q: 0.5 },
        reverb: { enabled: true, mix: 15, decay: 1.0 },
        delay: { enabled: false, time: 150, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -18, ratio: 3.5 },
      },
      sound: { sustain: 180, fade: 80, attack: 0, rate: 1.0, volume: 1 },
    },
    {
      id: "country",
      name: "Country",
      description: "Nashville studio sound",
      icon: "🤠",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 8000, Q: 0.5 },
        reverb: { enabled: true, mix: 25, decay: 1.5 },
        delay: { enabled: true, time: 250, feedback: 15, mix: 10 },
        compressor: { enabled: true, threshold: -20, ratio: 3 },
      },
      sound: { sustain: 220, fade: 100, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "electric-banjo",
      name: "Electric Banjo",
      description: "Bela Fleck — amplified and processed",
      icon: "⚡",
      effects: {
        distortion: { enabled: true, amount: 20 },
        filter: { enabled: true, type: "lowpass", frequency: 6000, Q: 1.5 },
        reverb: { enabled: true, mix: 20, decay: 1.2 },
        delay: { enabled: true, time: 200, feedback: 25, mix: 15 },
        compressor: { enabled: true, threshold: -15, ratio: 4 },
      },
      sound: { sustain: 200, fade: 90, attack: 0, rate: 1.0, volume: 2 },
    },
  ],

  violin: [
    {
      id: "clean",
      name: "Clean",
      description: "Pure acoustic violin",
      icon: "🎻",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 300, fade: 150, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "chamber",
      name: "Chamber",
      description: "Small ensemble room, warm resonance",
      icon: "🏠",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 10000, Q: 0.3 },
        reverb: { enabled: true, mix: 35, decay: 2.5 },
        delay: { enabled: false, time: 200, feedback: 5, mix: 3 },
        compressor: { enabled: true, threshold: -22, ratio: 2 },
      },
      sound: { sustain: 400, fade: 200, attack: 10, rate: 1.0, volume: 0 },
    },
    {
      id: "cinematic",
      name: "Cinematic",
      description: "Hollywood score — lush and epic",
      icon: "🎬",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: true, type: "lowpass", frequency: 8000, Q: 0.5 },
        reverb: { enabled: true, mix: 55, decay: 4.0 },
        delay: { enabled: true, time: 350, feedback: 20, mix: 15 },
        compressor: { enabled: true, threshold: -20, ratio: 3 },
      },
      sound: { sustain: 500, fade: 300, attack: 40, rate: 1.0, volume: 2 },
    },
    {
      id: "dark-strings",
      name: "Dark Strings",
      description: "Moody, low-filtered, noir soundtrack",
      icon: "🌑",
      effects: {
        distortion: { enabled: false, amount: 5 },
        filter: { enabled: true, type: "lowpass", frequency: 3000, Q: 1.0 },
        reverb: { enabled: true, mix: 40, decay: 3.0 },
        delay: { enabled: false, time: 300, feedback: 15, mix: 10 },
        compressor: { enabled: true, threshold: -22, ratio: 2.5 },
      },
      sound: { sustain: 400, fade: 250, attack: 20, rate: 0.95, volume: -1 },
    },
    {
      id: "electric-violin",
      name: "Electric Violin",
      description: "Lindsey Stirling — processed, modern",
      icon: "⚡",
      effects: {
        distortion: { enabled: true, amount: 25 },
        filter: { enabled: true, type: "lowpass", frequency: 6000, Q: 1.5 },
        reverb: { enabled: true, mix: 25, decay: 1.5 },
        delay: { enabled: true, time: 250, feedback: 30, mix: 20 },
        compressor: { enabled: true, threshold: -15, ratio: 4 },
      },
      sound: { sustain: 300, fade: 120, attack: 0, rate: 1.0, volume: 2 },
    },
  ],

  harp: [
    {
      id: "clean",
      name: "Clean",
      description: "Pure concert harp",
      icon: "🎵",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 350, fade: 200, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "angelic",
      name: "Angelic",
      description: "Heavenly reverb, floating in space",
      icon: "👼",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 12000, Q: 0.3 },
        reverb: { enabled: true, mix: 65, decay: 4.5 },
        delay: { enabled: true, time: 400, feedback: 25, mix: 20 },
        compressor: { enabled: true, threshold: -25, ratio: 2 },
      },
      sound: { sustain: 500, fade: 350, attack: 30, rate: 1.0, volume: -2 },
    },
    {
      id: "celtic",
      name: "Celtic",
      description: "Irish folk, warm and intimate",
      icon: "☘️",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 8000, Q: 0.5 },
        reverb: { enabled: true, mix: 25, decay: 2.0 },
        delay: { enabled: false, time: 200, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -20, ratio: 2.5 },
      },
      sound: { sustain: 300, fade: 150, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "mystical",
      name: "Mystical",
      description: "Fantasy soundtrack, enchanted forest",
      icon: "🧙",
      effects: {
        distortion: { enabled: false, amount: 3 },
        filter: { enabled: true, type: "bandpass", frequency: 2500, Q: 2.0 },
        reverb: { enabled: true, mix: 55, decay: 3.5 },
        delay: { enabled: true, time: 500, feedback: 40, mix: 30 },
        compressor: { enabled: true, threshold: -22, ratio: 2 },
      },
      sound: { sustain: 450, fade: 300, attack: 50, rate: 0.92, volume: -3 },
    },
  ],

  saxophone: [
    {
      id: "clean",
      name: "Clean",
      description: "Pure saxophone tone",
      icon: "🎷",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 250, fade: 120, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "smoky-jazz",
      name: "Smoky Jazz",
      description: "Late night club, intimate and warm",
      icon: "🌙",
      effects: {
        distortion: { enabled: false, amount: 5 },
        filter: { enabled: true, type: "lowpass", frequency: 5000, Q: 0.7 },
        reverb: { enabled: true, mix: 35, decay: 2.5 },
        delay: { enabled: false, time: 200, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -20, ratio: 3 },
      },
      sound: { sustain: 350, fade: 180, attack: 10, rate: 1.0, volume: -1 },
    },
    {
      id: "smooth-jazz",
      name: "Smooth Jazz",
      description: "Kenny G — polished, silky",
      icon: "✨",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: true, type: "lowpass", frequency: 7000, Q: 0.5 },
        reverb: { enabled: true, mix: 30, decay: 2.0 },
        delay: { enabled: true, time: 300, feedback: 20, mix: 15 },
        compressor: { enabled: true, threshold: -18, ratio: 3.5 },
      },
      sound: { sustain: 300, fade: 150, attack: 5, rate: 1.0, volume: 0 },
    },
    {
      id: "funky-sax",
      name: "Funky Sax",
      description: "James Brown horns — punchy and raw",
      icon: "🕺",
      effects: {
        distortion: { enabled: true, amount: 15 },
        filter: { enabled: true, type: "highpass", frequency: 500, Q: 1.0 },
        reverb: { enabled: false, mix: 10, decay: 0.8 },
        delay: { enabled: false, time: 150, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -12, ratio: 5 },
      },
      sound: { sustain: 150, fade: 60, attack: 0, rate: 1.0, volume: 3 },
    },
  ],

  trumpet: [
    {
      id: "clean",
      name: "Clean",
      description: "Pure trumpet tone",
      icon: "🎺",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 250, fade: 120, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "jazz-club",
      name: "Jazz Club",
      description: "Miles Davis — warm, muted, intimate",
      icon: "🌙",
      effects: {
        distortion: { enabled: false, amount: 5 },
        filter: { enabled: true, type: "lowpass", frequency: 4000, Q: 0.8 },
        reverb: { enabled: true, mix: 30, decay: 2.0 },
        delay: { enabled: false, time: 200, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -20, ratio: 3 },
      },
      sound: { sustain: 300, fade: 150, attack: 10, rate: 1.0, volume: -2 },
    },
    {
      id: "mariachi",
      name: "Mariachi",
      description: "Bright, festive, bold",
      icon: "🪅",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: true, type: "highpass", frequency: 600, Q: 1.0 },
        reverb: { enabled: true, mix: 25, decay: 1.5 },
        delay: { enabled: false, time: 150, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -15, ratio: 4 },
      },
      sound: { sustain: 200, fade: 80, attack: 0, rate: 1.0, volume: 3 },
    },
    {
      id: "orchestral",
      name: "Orchestral",
      description: "Concert hall, full and resonant",
      icon: "🏛️",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 10000, Q: 0.3 },
        reverb: { enabled: true, mix: 45, decay: 3.5 },
        delay: { enabled: false, time: 300, feedback: 5, mix: 3 },
        compressor: { enabled: true, threshold: -22, ratio: 2.5 },
      },
      sound: { sustain: 400, fade: 250, attack: 15, rate: 1.0, volume: 0 },
    },
  ],

  flute: [
    {
      id: "clean",
      name: "Clean",
      description: "Pure concert flute",
      icon: "🎵",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 300, fade: 150, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "ethereal",
      name: "Ethereal",
      description: "Floating, airy, otherworldly",
      icon: "🌊",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 10000, Q: 0.3 },
        reverb: { enabled: true, mix: 60, decay: 4.5 },
        delay: { enabled: true, time: 450, feedback: 35, mix: 30 },
        compressor: { enabled: true, threshold: -25, ratio: 2 },
      },
      sound: { sustain: 500, fade: 350, attack: 50, rate: 1.0, volume: -2 },
    },
    {
      id: "celtic",
      name: "Celtic",
      description: "Irish tin whistle vibe, folk",
      icon: "☘️",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: true, type: "highpass", frequency: 500, Q: 0.5 },
        reverb: { enabled: true, mix: 25, decay: 1.5 },
        delay: { enabled: false, time: 200, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -20, ratio: 2.5 },
      },
      sound: { sustain: 250, fade: 120, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "pan-flute",
      name: "Pan Flute",
      description: "Zamfir — breathy, mystical",
      icon: "🏔️",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: true, type: "lowpass", frequency: 5000, Q: 0.5 },
        reverb: { enabled: true, mix: 45, decay: 3.0 },
        delay: { enabled: true, time: 350, feedback: 20, mix: 15 },
        compressor: { enabled: true, threshold: -22, ratio: 2 },
      },
      sound: { sustain: 350, fade: 200, attack: 20, rate: 0.95, volume: -1 },
    },
  ],

  clarinet: [
    {
      id: "clean",
      name: "Clean",
      description: "Pure clarinet tone",
      icon: "🎵",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 250, fade: 120, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "jazz-clarinet",
      name: "Jazz",
      description: "Benny Goodman — warm swing era",
      icon: "🎩",
      effects: {
        distortion: { enabled: false, amount: 5 },
        filter: { enabled: true, type: "lowpass", frequency: 6000, Q: 0.7 },
        reverb: { enabled: true, mix: 30, decay: 2.0 },
        delay: { enabled: false, time: 200, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -20, ratio: 3 },
      },
      sound: { sustain: 300, fade: 150, attack: 5, rate: 1.0, volume: 0 },
    },
    {
      id: "klezmer",
      name: "Klezmer",
      description: "Eastern European folk, expressive",
      icon: "💫",
      effects: {
        distortion: { enabled: true, amount: 8 },
        filter: { enabled: true, type: "bandpass", frequency: 3000, Q: 2.0 },
        reverb: { enabled: true, mix: 25, decay: 1.5 },
        delay: { enabled: false, time: 200, feedback: 15, mix: 8 },
        compressor: { enabled: true, threshold: -18, ratio: 3.5 },
      },
      sound: { sustain: 250, fade: 100, attack: 0, rate: 1.05, volume: 1 },
    },
    {
      id: "dark-woody",
      name: "Dark & Woody",
      description: "Low register, rich and mellow",
      icon: "🌑",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: true, type: "lowpass", frequency: 3500, Q: 0.8 },
        reverb: { enabled: true, mix: 30, decay: 2.5 },
        delay: { enabled: false, time: 250, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -22, ratio: 2.5 },
      },
      sound: { sustain: 350, fade: 200, attack: 10, rate: 0.95, volume: -1 },
    },
  ],

  bass: [
    {
      id: "clean",
      name: "Clean",
      description: "Pure bass, no processing",
      icon: "🎸",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 200, fade: 100, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "techno",
      name: "Techno",
      description: "Electronic, punchy, short decay",
      icon: "🔊",
      effects: {
        distortion: { enabled: true, amount: 30 },
        filter: { enabled: true, type: "lowpass", frequency: 2500, Q: 3.0 },
        reverb: { enabled: false, mix: 5, decay: 0.5 },
        delay: { enabled: false, time: 100, feedback: 5, mix: 3 },
        compressor: { enabled: true, threshold: -12, ratio: 8 },
      },
      sound: { sustain: 100, fade: 40, attack: 0, rate: 1.0, volume: 3 },
    },
    {
      id: "sub-bass",
      name: "Sub Bass",
      description: "Deep, rumbling, feels it in your chest",
      icon: "🌊",
      effects: {
        distortion: { enabled: false, amount: 5 },
        filter: { enabled: true, type: "lowpass", frequency: 800, Q: 1.5 },
        reverb: { enabled: false, mix: 5, decay: 0.5 },
        delay: { enabled: false, time: 150, feedback: 5, mix: 3 },
        compressor: { enabled: true, threshold: -15, ratio: 6 },
      },
      sound: { sustain: 250, fade: 150, attack: 10, rate: 0.8, volume: 4 },
    },
    {
      id: "acid",
      name: "Acid",
      description: "TB-303 style — squelchy resonant filter",
      icon: "🧪",
      effects: {
        distortion: { enabled: true, amount: 40 },
        filter: { enabled: true, type: "lowpass", frequency: 1500, Q: 8.0 },
        reverb: { enabled: false, mix: 5, decay: 0.5 },
        delay: { enabled: true, time: 150, feedback: 30, mix: 15 },
        compressor: { enabled: true, threshold: -15, ratio: 5 },
      },
      sound: { sustain: 120, fade: 50, attack: 0, rate: 1.0, volume: 2 },
    },
    {
      id: "funk-bass",
      name: "Funk",
      description: "Slap bass, tight and groovy",
      icon: "🕺",
      effects: {
        distortion: { enabled: true, amount: 15 },
        filter: { enabled: true, type: "highpass", frequency: 200, Q: 1.0 },
        reverb: { enabled: false, mix: 5, decay: 0.5 },
        delay: { enabled: false, time: 100, feedback: 5, mix: 3 },
        compressor: { enabled: true, threshold: -15, ratio: 5 },
      },
      sound: { sustain: 120, fade: 50, attack: 0, rate: 1.0, volume: 2 },
    },
    {
      id: "dubstep",
      name: "Dubstep",
      description: "Wobble bass, heavy and aggressive",
      icon: "💥",
      effects: {
        distortion: { enabled: true, amount: 65 },
        filter: { enabled: true, type: "lowpass", frequency: 1200, Q: 6.0 },
        reverb: { enabled: false, mix: 10, decay: 0.8 },
        delay: { enabled: false, time: 100, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -10, ratio: 10 },
      },
      sound: { sustain: 150, fade: 60, attack: 0, rate: 0.85, volume: 4 },
    },
    {
      id: "synthwave",
      name: "Synthwave",
      description: "80s retro, neon-lit bass line",
      icon: "🌆",
      effects: {
        distortion: { enabled: true, amount: 20 },
        filter: { enabled: true, type: "lowpass", frequency: 3000, Q: 2.0 },
        reverb: { enabled: true, mix: 20, decay: 1.5 },
        delay: { enabled: true, time: 300, feedback: 25, mix: 15 },
        compressor: { enabled: true, threshold: -18, ratio: 4 },
      },
      sound: { sustain: 180, fade: 80, attack: 5, rate: 1.0, volume: 2 },
    },
  ],

  "og-bass": [
    {
      id: "clean",
      name: "Clean",
      description: "The original, unprocessed",
      icon: "🎸",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 300, fade: 150, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "deep-og",
      name: "Deep OG",
      description: "Sub-heavy, extended sustain",
      icon: "🌊",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: true, type: "lowpass", frequency: 1200, Q: 1.5 },
        reverb: { enabled: false, mix: 5, decay: 0.5 },
        delay: { enabled: false, time: 150, feedback: 5, mix: 3 },
        compressor: { enabled: true, threshold: -15, ratio: 5 },
      },
      sound: { sustain: 400, fade: 200, attack: 10, rate: 0.85, volume: 3 },
    },
    {
      id: "warm-og",
      name: "Warm OG",
      description: "Rounded low-end, cozy vibe",
      icon: "🔥",
      effects: {
        distortion: { enabled: true, amount: 10 },
        filter: { enabled: true, type: "lowpass", frequency: 3000, Q: 0.7 },
        reverb: { enabled: true, mix: 15, decay: 1.0 },
        delay: { enabled: false, time: 200, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -18, ratio: 3 },
      },
      sound: { sustain: 300, fade: 150, attack: 0, rate: 1.0, volume: 1 },
    },
    {
      id: "gritty-og",
      name: "Gritty OG",
      description: "Distorted, punchy, aggressive",
      icon: "💥",
      effects: {
        distortion: { enabled: true, amount: 45 },
        filter: { enabled: true, type: "lowpass", frequency: 4000, Q: 2.0 },
        reverb: { enabled: false, mix: 5, decay: 0.5 },
        delay: { enabled: false, time: 100, feedback: 5, mix: 3 },
        compressor: { enabled: true, threshold: -12, ratio: 8 },
      },
      sound: { sustain: 200, fade: 80, attack: 0, rate: 1.0, volume: 3 },
    },
    {
      id: "retro-og",
      name: "Retro OG",
      description: "80s synth bass feel",
      icon: "🌆",
      effects: {
        distortion: { enabled: true, amount: 20 },
        filter: { enabled: true, type: "lowpass", frequency: 2500, Q: 2.5 },
        reverb: { enabled: true, mix: 20, decay: 1.5 },
        delay: { enabled: true, time: 250, feedback: 20, mix: 10 },
        compressor: { enabled: true, threshold: -18, ratio: 4 },
      },
      sound: { sustain: 250, fade: 120, attack: 5, rate: 1.0, volume: 2 },
    },
  ],

  drums: [
    {
      id: "clean",
      name: "Clean",
      description: "Raw, unprocessed drums",
      icon: "🥁",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 150, fade: 50, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "808",
      name: "808",
      description: "Roland TR-808 — deep, booming",
      icon: "🔊",
      effects: {
        distortion: { enabled: false, amount: 10 },
        filter: { enabled: true, type: "lowpass", frequency: 5000, Q: 1.0 },
        reverb: { enabled: true, mix: 15, decay: 0.8 },
        delay: { enabled: false, time: 150, feedback: 5, mix: 3 },
        compressor: { enabled: true, threshold: -12, ratio: 6 },
      },
      sound: { sustain: 200, fade: 80, attack: 0, rate: 0.9, volume: 3 },
    },
    {
      id: "lofi-drums",
      name: "Lo-fi",
      description: "Dusty, vinyl crackle, mellow",
      icon: "📻",
      effects: {
        distortion: { enabled: true, amount: 15 },
        filter: { enabled: true, type: "lowpass", frequency: 3500, Q: 0.8 },
        reverb: { enabled: true, mix: 20, decay: 1.2 },
        delay: { enabled: false, time: 200, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -20, ratio: 4 },
      },
      sound: { sustain: 130, fade: 50, attack: 0, rate: 0.95, volume: -2 },
    },
    {
      id: "industrial",
      name: "Industrial",
      description: "Nine Inch Nails — harsh, metallic",
      icon: "🏭",
      effects: {
        distortion: { enabled: true, amount: 70 },
        filter: { enabled: true, type: "highpass", frequency: 500, Q: 2.0 },
        reverb: { enabled: true, mix: 25, decay: 1.0 },
        delay: { enabled: false, time: 100, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -10, ratio: 10 },
      },
      sound: { sustain: 100, fade: 30, attack: 0, rate: 1.0, volume: 4 },
    },
    {
      id: "trap",
      name: "Trap",
      description: "Hi-hat rolls, heavy 808 kick",
      icon: "💎",
      effects: {
        distortion: { enabled: false, amount: 10 },
        filter: { enabled: true, type: "lowpass", frequency: 8000, Q: 1.0 },
        reverb: { enabled: true, mix: 20, decay: 1.0 },
        delay: { enabled: false, time: 100, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -15, ratio: 6 },
      },
      sound: { sustain: 180, fade: 60, attack: 0, rate: 1.0, volume: 2 },
    },
    {
      id: "boom-bap",
      name: "Boom Bap",
      description: "90s hip-hop — punchy, warm",
      icon: "🎤",
      effects: {
        distortion: { enabled: true, amount: 10 },
        filter: { enabled: true, type: "lowpass", frequency: 6000, Q: 0.8 },
        reverb: { enabled: true, mix: 15, decay: 0.8 },
        delay: { enabled: false, time: 150, feedback: 10, mix: 5 },
        compressor: { enabled: true, threshold: -18, ratio: 5 },
      },
      sound: { sustain: 150, fade: 50, attack: 0, rate: 1.0, volume: 1 },
    },
  ],

  percussion: [
    {
      id: "clean",
      name: "Clean",
      description: "Raw percussion",
      icon: "🥁",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 20000, Q: 0.5 },
        reverb: { enabled: false, mix: 0, decay: 1.0 },
        delay: { enabled: false, time: 250, feedback: 0, mix: 0 },
        compressor: { enabled: false, threshold: 0, ratio: 1 },
      },
      sound: { sustain: 180, fade: 60, attack: 0, rate: 1.0, volume: 0 },
    },
    {
      id: "electronic",
      name: "Electronic",
      description: "Processed, synthetic hits",
      icon: "🤖",
      effects: {
        distortion: { enabled: true, amount: 25 },
        filter: { enabled: true, type: "lowpass", frequency: 5000, Q: 2.0 },
        reverb: { enabled: false, mix: 10, decay: 0.5 },
        delay: { enabled: true, time: 150, feedback: 25, mix: 15 },
        compressor: { enabled: true, threshold: -15, ratio: 6 },
      },
      sound: { sustain: 120, fade: 40, attack: 0, rate: 1.0, volume: 2 },
    },
    {
      id: "ambient-perc",
      name: "Ambient",
      description: "Spacious, atmospheric, tribal echoes",
      icon: "🌊",
      effects: {
        distortion: { enabled: false, amount: 0 },
        filter: { enabled: false, type: "lowpass", frequency: 8000, Q: 0.5 },
        reverb: { enabled: true, mix: 55, decay: 3.5 },
        delay: { enabled: true, time: 400, feedback: 35, mix: 25 },
        compressor: { enabled: true, threshold: -22, ratio: 2 },
      },
      sound: { sustain: 300, fade: 200, attack: 20, rate: 1.0, volume: -2 },
    },
    {
      id: "tribal",
      name: "Tribal",
      description: "African/Brazilian — earthy and rhythmic",
      icon: "🌍",
      effects: {
        distortion: { enabled: false, amount: 5 },
        filter: { enabled: true, type: "highpass", frequency: 300, Q: 0.8 },
        reverb: { enabled: true, mix: 30, decay: 2.0 },
        delay: { enabled: false, time: 200, feedback: 15, mix: 8 },
        compressor: { enabled: true, threshold: -18, ratio: 3.5 },
      },
      sound: { sustain: 200, fade: 80, attack: 0, rate: 1.0, volume: 1 },
    },
  ],
};

export function getPresetsForInstrument(instrumentId) {
  return presets[instrumentId] || presets.piano;
}

export function getPresetById(instrumentId, presetId) {
  const list = getPresetsForInstrument(instrumentId);
  return list.find((p) => p.id === presetId) || null;
}

export default presets;
